site_name: Numérique et Sciences Informatiques Terminale
theme:
 name: material
 features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - header.autohide
 language: fr
 palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: brown
      accent: deep orange 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: brown
      accent: deep orange

plugins:
  - search


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true

copyright:  CC BY-SA / C. Arduini

repo_url: https://github.com/abrugiere/test

repo_name: abrugiere/test

nav:
  - Accueil: 'index.md'
  - Intro: '0.0.INTRO.md'
  - Rappels de 1ère: '0.1.PREM.md'
  - Structures de données: '1.0.STRUCT.md'
  - Bases de données: '2.0.BDD.md'
  - Architecture: '3.0.ARCHI.md'
  - Programmation: '4.0.LANG.md'
  - Algorithmique: '5.0.ALGO.md'
  - Révisions: '6.0.REV.md'
